title: Data 198
description: Introduction to Real World Data Science
theme: just-the-docs

url: https://jegeronimo.github.io/dss-data-198

aux_links:
  Template Repository: https://github.com/jegeronimo/dss-data-198
