title: Data 198
description: Introduction to Real World Data Science
logo: assets/site_images/dsslogo.png
author: Directors of Academic Development
email: dss.data198@gmail.com
theme: just-the-docs
just_the_docs:
  favicon:
    path: assets/site_images/favicon.png
#baseurl: # the subpath of your site, e.g. /blog

#url: https://dss-data-198.github.io # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]


# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.3.3
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  bCourses Site: 
    - 'https://bcourses.berkeley.edu/courses/1534410'
  Syllabus: 
    - 'https://docs.google.com/document/d/1Dz6GFDBfU3S_VzzhqRJwBhNhM4sqR1jQ02erfx0rhFQ/edit?usp=sharing'
  Data Science Society:
    - url: 'https://dssberkeley.com'


# Collections for website data
collections: 
  acknowledgers:
  staffers:
  modules:
  schedules:
  announcements:


defaults: #Used to define the default settings for different collections or types of content
  - scope: #Determines where the default settings should apply.
      path: "" #The path where the default settings should apply to, if "" means it will apply globally to the specific type across the site
      type: staffers #The specific collection
    values: 
      layout: staffer #which specific layout to use
      subpath: "/assets/images/" #what's the default subpath for this file
  - scope:
      path: ""
      type: modules
    values:
      layout: module
  - scope:
      path: ""
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ""
      type: announcements
    values:
      layout: announcement
  - scope:
      path: ""
      type: acknowledgers
    values:
      layout: acknowledger
      subpath: "/assets/images/"


#After site is built, but before it is published!
compress_html: #compresses HTML output, making the HTML files smaller, thus increasing performance of the website
  clippings: all #all unnecessary parts or "cippings" of HTML are removed (redundant tags and the like)
  comments: all #removes all comments
  endings: all #remove optional closing tags (tags which don't need closing to still work)
  startings: [] #no specific action to compress the beginning of HTML elements
  blanklines: false #blank lines not removed, as they are valuable in reading code easily
  profile: false #doesn't generate a profiling report

plugins:
  - jekyll-seo-tag

markdown: kramdown #specifies to use kramdown, a Ruby gem that parses markdowns and converts it to HTML
kramdown:
  input: GFM #Input is GitHub Flavored Markdown, so the same one that GitHub uses
  hard_wrap: false #Single newlines in the Markdown will not translate into <br> tagsl, so empty lines just signify new <p>
  enable_coderay: false #Doesn't enable CodeRay, a Ruby Gem syntax highlighter
safe: false #Allows for the use of custom plugins and non-whitelisted Ruby gems in your Jekyll project