title: Data 198
description: Introduction to Real World Data Science
theme: just-the-docs

url: https://jegeronimo.github.io/dss-data-198

aux_links:
  Data Science Society at Berkeley: https://dssberkeley.com/